analysis:
  enable_analysis: true
  generate_excel_summary: true
  generate_interactive_plots: false
anonymization:
  attributes:
    insensitive_attributes:
    - DR_NO
    - Time_occured
    - Premis
    - Weapon
    - Status
    quasi_identifiers:
    - Victim_age
    - Victim_sex
    - Victim_descent
    - LAT
    - LON
    sensitive_attributes:
    - Crime_Code
  delete_after_evaluation: true
  enable_anonymization: true
  hierarchies:
    Victim_age: src/anonymization/anonymARXij/src/hierarchies/hierarchy_age_4.csv
    Victim_descent: src/anonymization/anonymARXij/src/hierarchies/hierarchy_descent.csv
    Victim_sex: src/anonymization/anonymARXij/src/hierarchies/hierarchy_sex.csv
  hierarchy_config:
    LAT: 10
    LON: 10
  models:
    k_anonymity: 15
    l_diversity:
      attribute: Crime_Code
      value: 3
  suppression_limit: 0.05
dataset:
  path: datasets/original/crimeData.csv
  separator: ','
  target_column: Status
  test_size: 0.2
hybrid:
  enable_hybrid: false
  epochs: 30
  execution_order: synthetic_first
  k_anonymity: 5
  l_diversity: 3
  num_generated_rows: 5000
  reuse_params: true
  save_intermediate_files: false
  synthesizer: CTGAN
preprocessing:
  encoding_type: binary
  handle_missing_values: drop
synthesis:
  enable_synthetic_generation: false
  synthesizers:
    CTGAN:
      class_name: CTGANSynthesizer
      custom_generated_rows: 10000
      enabled: true
      import_path: sdv.single_table
      num_generated_rows: same_as_original
      params:
        epochs: 50
      row_multiplier: 8
    CustomSynthesizer:
      class_name: CustomSynthesizer
      custom_generated_rows: 7000
      enabled: false
      import_path: custom.custom_synthesizer
      num_generated_rows: custom
      params:
        noise_factor: 0.2
      row_multiplier: 8
    GaussianCopula:
      class_name: GaussianCopulaSynthesizer
      custom_generated_rows: 5000
      enabled: true
      import_path: sdv.single_table
      num_generated_rows: same_as_original
      params: {}
    TVAE:
      class_name: TVAESynthesizer
      custom_generated_rows: 5000
      enabled: true
      import_path: sdv.single_table
      num_generated_rows: same_as_original
      params:
        epochs: 50
      row_multiplier: 8
utility:
  enable_utility_evaluation: true
  metrics:
    AUC-ROC: true
    Accuracy: true
    CohenKappa: true
    F1: true
    LogLoss: true
    MCC: true
    Precision: true
    Recall: true
  models:
    DecisionTree: true
    KNN: true
    LogisticRegression: true
    RandomForest: true
    SVM: true
    XGBoost: false
