dataset: crimeData
values:
  custom_generated_rows: []
  epochs:
  - 100
  - 300
  - 500
  - 1000
  k_anonymity:
  - 5
  - 10
  - 20
  suppression_limit:
  - 0.01
  - 0.1
  - 0.2
  - 0.3
  - 0.5
varied_parameters:
- suppression_limit
- k_anonymity
- epochs
- custom_generated_rows
