dataset:
  path: "datasets/original/loan.csv" # Path to the dataset
  separator: "," # Delimiter used in the dataset (e.g., "," or "\t")
  target_column: "LoanAmount" # Column to exclude from encoding

preprocessing:
  handle_missing_values: "drop" # Options: "drop", "mean", "median", "mode"
  encoding_type: "binary" # Type of encoding, currently only "binary" is supported
