dataset:
  path: "datasets/original/loan.csv" # Path to the dataset
  separator: "," # Delimiter used in the dataset (e.g., "," or "\t")
  target_column: "Loan_Status" # Name of the target column
  test_size: 0.5

preprocessing:
  handle_missing_values: "drop" # Options: "drop", "mean", "median", "mode"
  encoding_type: "binary" # Type of encoding, currently only "binary" is supported

synthesis:
  enable_synthetic_generation: true # Set to false to skip
  synthesizers:
    CTGAN:
      enabled: true
      import_path: "sdv.single_table"
      class_name: "CTGANSynthesizer"
      params:
        epochs: 50
      num_generated_rows: "same_as_original" # Options: "same_as_original", "custom"
      custom_generated_rows: 10000 # Only used if num_generated_rows is "custom"

    TVAE:
      enabled: true
      import_path: "sdv.single_table"
      class_name: "TVAESynthesizer"
      params:
        epochs: 50
      num_generated_rows: "same_as_original" #Options: "same_as_original", "custom"
      custom_generated_rows: 5000 # TVAE will generate 5000 rows

    GaussianCopula:
      enabled: true
      import_path: "sdv.single_table"
      class_name: "GaussianCopulaSynthesizer"
      params: {}
      num_generated_rows: "same_as_original"

    CustomSynthesizer:
      enabled: false # Set to true if using a custom one
      import_path: "custom.custom_synthesizer"
      class_name: "CustomSynthesizer"
      params:
        noise_factor: 0.2
      num_generated_rows: "custom"
      custom_generated_rows: 7000

utility:
  models:
    LogisticRegression: true
    KNN: true
    RandomForest: true
    DecisionTree: true
    SVM: true

  metrics:
    Accuracy: true
    Precision: true
    Recall: true
    F1: true
    AUC-ROC: true
    LogLoss: true # Disabled for models that don't support probabilities
    CohenKappa: true
    MCC: true
