dataset:
  path: "datasets/original/studentPerformance.csv" # Path to the dataset
  separator: ";" # Delimiter used in the dataset (e.g., "," or "\t")
  target_column: "Target"

preprocessing:
  handle_missing_values: "drop" # Options: "drop", "mean", "median", "mode"
  encoding_type: "binary" # Type of encoding, currently only "binary" is supported

synthesis:
  enable_synthetic_generation: true # Set to false to skip
  synthesizer_type: "GaussianCopula" # Options: "CTGAN", "TVAE", "GaussianCopula"
  num_epochs: 50 # Number of training epochs
  num_generated_rows: "same_as_original" # Options: "same_as_original", "custom"
  custom_generated_rows: 10000 # If num_generated_rows is "custom", specify row count

utility:
  test_size: 0.2 # Proportion of the dataset used for testing
  models:
    LogisticRegression: false
    KNN: true
    RandomForest: false
    DecisionTree: false
    SVM: false
