dataset:
  path: "datasets/original/loan.csv" # Path to the dataset
  separator: "," # Delimiter used in the dataset (e.g., "," or "\t")
  target_column: "LoanAmount" # Column to exclude from encoding

preprocessing:
  handle_missing_values: "drop" # Options: "drop", "mean", "median", "mode"
  encoding_type: "binary" # Type of encoding, currently only "binary" is supported

synthesis:
  enable_synthetic_generation: true # Set to false to disable
  test_size: 0.2 # Proportion of data NOT used for synthetic generation
