dataset:
  path: "datasets/original/studentMathScores.csv" # Path to the dataset
  separator: ";" # Delimiter used in the dataset (e.g., "," or "\t")
  target_column: "G3" # Name of the target column
  test_size: 0.2

preprocessing:
  handle_missing_values: "drop" # Options: "drop", "mean", "median", "mode"
  encoding_type: "binary" # Type of encoding, currently only "binary" is supported

synthesis:
  enable_synthetic_generation: false # Set to false to skip
  synthesizers:
    CTGAN:
      enabled: true
      import_path: "sdv.single_table"
      class_name: "CTGANSynthesizer"
      params:
        epochs: 50
      num_generated_rows: "same_as_original" # Options: "same_as_original", "custom"
      custom_generated_: 10000 # Only used if num_generated_rows is "custom"
    TVAE:
      enabled: false
      import_path: "sdv.single_table"
      class_name: "TVAESynthesizer"
      params:
        epochs: 50
      num_generated_rows: "same_as_original" #Options: "same_as_original", "custom"
      custom_generated_rows: 5000 # TVAE will generate 5000 rows
    GaussianCopula:
      enabled: false
      import_path: "sdv.single_table"
      class_name: "GaussianCopulaSynthesizer"
      params: {}
      num_generated_rows: "same_as_original"
    CustomSynthesizer:
      enabled: false # Set to true if using a custom one
      import_path: "custom.custom_synthesizer"
      class_name: "CustomSynthesizer"
      params:
        noise_factor: 0.2
      num_generated_rows: "custom"
      custom_generated_rows: 7000

anonymization:
  enable_anonymization: true
  anonymized_output: "datasets/anonymized/studentMathScore_anonymized.csv"
  suppression_limit: 0.1
  attributes:
    quasi_identifiers:
      - "sex"
      - "age"
      - "famsize"
    sensitive_attributes:
      - "health"
    insensitive_attributes:
      - "traveltime"
      - "studytime"
      - "schoolsup"
      - "paid"
      - "higher"
      - "romantic"
      - "famrel"
      - "freetime"
      - "Dalc"
      - "Walc"



  hierarchies:
    "sex": "src/anonymization/anonymARXij/src/hierarchies_studentMathScores/sex.csv"
    "age": "src/anonymization/anonymARXij/src/hierarchies_studentMathScores/age.csv"
    "famsize": "src/anonymization/anonymARXij/src/hierarchies_studentMathScores/famsize.csv"

  hierarchy_config: {}

  models:
    k_anonymity: 5
    l_diversity:
      attribute: "Scholarship_holder"
      value: 2

utility:
  enable_utility_evaluation: true
  models:
    LogisticRegression: true
    KNN: true
    RandomForest: true
    DecisionTree: true
    SVM: false
    XGBoost: false

  metrics:
    Accuracy: true
    Precision: true
    Recall: true
    F1: true
    AUC-ROC: true
    LogLoss: true # Disabled for models that don't support probabilities
    CohenKappa: true
    MCC: true
