import pandas as pd
from modelOperations.ml_data_preprocessing import prepare_original_data, prepare_synthetic_data
from modelOperations.model_training import train_models

def run_utility(cleaned_data, test_set, target_column, enable_synthetic, config, synthetic_datasets=None, anonymous_data=None, hybrid_data=None, logger=None):
    """
    Handles dataset preparation and model training.
    """

    print("Preparing datasets for machine learning...")
    if logger:
        logger.info("Preparing datasets for machine learning...")

    # Extract X (features) and y (target) from the training set
    X_train_original = cleaned_data.drop(columns=[target_column])
    y_train_original = cleaned_data[target_column]

    # Extract X_test and y_test from the test set
    X_test_original = test_set.drop(columns=[target_column])
    y_test_original = test_set[target_column]

    print(f"Original Data - Training Size: {len(X_train_original)}, Testing Size: {len(X_test_original)}")
    if logger:
        logger.info(f"Original Data - Training Size: {len(X_train_original)}, Testing Size: {len(X_test_original)}")

    # Dictionary to store all datasets
    datasets = {"Original": (X_train_original, y_train_original)}

    # Handle synthetic datasets if provided
    if enable_synthetic and synthetic_datasets:
        for synth_name, synthetic_data in synthetic_datasets.items():
            print(f"\nProcessing synthetic dataset generated by {synth_name}...")
            if logger:
                logger.info(f"Processing synthetic dataset generated by {synth_name}...")
            X_synth = synthetic_data.drop(columns=[target_column])
            y_synth = synthetic_data[target_column]
            datasets[synth_name] = (X_synth, y_synth)
            print(f"Synthetic Data ({synth_name}) - Training Size: {len(X_synth)}")
            if logger:
                logger.info(f"Synthetic Data ({synth_name}) - Training Size: {len(X_synth)}")

    # Handle anonymized dataset if provided
    if anonymous_data is not None:
        print("\nProcessing anonymized dataset...")
        if logger:
            logger.info("Processing anonymized dataset...")
        X_anon = anonymous_data.drop(columns=[target_column])
        y_anon = anonymous_data[target_column]
        datasets["Anonymous"] = (X_anon, y_anon)
        print(f"Anonymized Data - Training Size: {len(X_anon)}")
        if logger:
            logger.info(f"Anonymized Data - Training Size: {len(X_anon)}")
    
    if hybrid_data is not None:
        print("\nProcessing hybrid dataset...")
        if logger:
            logger.info("Processing hybrid dataset...")
        X_hybrid = hybrid_data.drop(columns=[target_column])
        y_hybrid = hybrid_data[target_column]
        datasets["Hybrid"] = (X_hybrid, y_hybrid)
        print(f"Hybrid Data - Training Size: {len(X_hybrid)}")
        if logger:
            logger.info(f"Hybrid Data - Training Size: {len(X_hybrid)}")

    # Train models on all available datasets
    print("\nTraining models on all datasets...")
    if logger:
        logger.info("Training models on all datasets...")
    trained_models = train_models(datasets, config)

    print("\nModel Training Completed.")
    if logger:
        logger.info("Model Training Completed.")
    return trained_models, X_test_original, y_test_original, datasets

if __name__ == "__main__":
    print(" This script is not meant to be run directly. It should be imported and used in `run_benchmarks.py`.")
