import pandas as pd
from modelOperations.ml_data_preprocessing import prepare_original_data, prepare_synthetic_data
from modelOperations.model_training import train_models

def run_utility(cleaned_data, synthetic_datasets, test_set, target_column, enable_synthetic, config):
    """
    Handles dataset preparation and model training.

    Parameters:
    - cleaned_data (DataFrame): The cleaned dataset (training only).
    - synthetic_datasets (dict): Dictionary mapping synthesizer names to synthetic datasets.
    - target_column (str): Target variable for ML models.
    - test_size (float): Proportion of dataset for testing.
    - enable_synthetic (bool): Whether to include synthetic data in training.
    - config (dict): Configuration dictionary.
    - test_set (DataFrame): The test set from preprocessing.

    Returns:
    - trained_models (dict): Dictionary of trained models.
    - X_test_original (DataFrame): Test set from original data.
    - y_test_original (Series): Target values for test set.
    - datasets (dict): Dictionary containing training datasets.
    """

    print("Preparing datasets for machine learning...")

    # Extract X (features) and y (target) from the training set
    X_train_original = cleaned_data.drop(columns=[target_column])
    y_train_original = cleaned_data[target_column]

    # Extract X_test and y_test from the test set
    X_test_original = test_set.drop(columns=[target_column])
    y_test_original = test_set[target_column]

    print(f"Original Data - Training Size: {len(X_train_original)}, Testing Size: {len(X_test_original)}")

    # Dictionary to store all datasets
    datasets = {"Original": (X_train_original, y_train_original)}

    # Handle multiple synthetic datasets
    if enable_synthetic and synthetic_datasets:
        for synth_name, synthetic_data in synthetic_datasets.items():
            print(f"\nProcessing synthetic dataset generated by {synth_name}...")
            # Process synthetic data without needing `prepare_synthetic_data`
            X_synth = synthetic_data.drop(columns=[target_column])
            y_synth = synthetic_data[target_column]

            # Assign the same test set from the original dataset
            datasets[synth_name] = (X_synth, y_synth) 
            print(f"Synthetic Data ({synth_name}) - Training Size: {len(X_synth)}")

    print("\nTraining models on all datasets...")
    trained_models = train_models(datasets, config)

    print("\nModel Training Completed.")
    return trained_models, X_test_original, y_test_original, datasets  # Pass back for evaluation


if __name__ == "__main__":
    print(" This script is not meant to be run directly. It should be imported and used in `run_benchmarks.py`.")
