import os
import yaml
from synthetic_pipeline.data_synthesis import generate_synthetic_datasets
from synthetic_pipeline.synthetic_evaluation import evaluate_synthetic_data, compare_data_distributions
from output_utils.report_generator import save_synthetic_data_report

def load_config(config_path="configs/benchmark_config.yaml"):
    """
    Loads the YAML configuration file.

    Parameters:
    - config_path (str): Path to the configuration YAML file.

    Returns:
    - config (dict): Dictionary containing configuration parameters.
    """
    with open(config_path, "r") as file:
        config = yaml.safe_load(file)
    return config

def run_synthetic(cleaned_data, dataset_name, target_column, output_dir, config, logger=None):
    """
    Handles synthetic data generation, evaluation, and reporting.

    Parameters:
    - cleaned_data (DataFrame): Preprocessed dataset.
    - dataset_name (str): Name of the dataset.
    - target_column (str): The target column for evaluation.
    - output_dir (str): Path to the output directory.
    - config (dict): Configuration dictionary.

    Returns:
    - synthetic_datasets (dict): Generated synthetic datasets.
   
    """
    # enable_synthetic = config["synthesis"]["enable_synthetic_generation"]

    # if not enable_synthetic:
    #     print("\nSynthetic Data Generation Skipped (Disabled in Configuration).")
    #     if logger:
    #         logger.info("Synthetic Data Generation Skipped (Disabled in Configuration).")
    #     return {} # Return empty dictionary and None for metadata

    print("\nStarting Synthetic Data Generation...")
    if logger:
        logger.info("Executing run_synthetic.....")


    # Generate synthetic datasets
    if logger:
        logger.info(f"[SYNTHETIC PIPELINE] executing run_synthetic for {dataset_name}...")
    synthetic_datasets, metadata = generate_synthetic_datasets(cleaned_data, dataset_name, config, logger=logger)
    print("\nSynthetic Data Generation Completed.")
    if logger:
        logger.info("[SYNTHETIC PIPELINE] Synthetic Data Generation Completed.")
        logger.info(f"[SYNTHETIC PIPELINE] Synthesizers used: {list(synthetic_datasets.keys())}")



    # Evaluate synthetic datasets
    quality_reports = {}
    for synth_name, synthetic_data in synthetic_datasets.items():
        print(f"\nEvaluating synthetic dataset generated by {synth_name}...")
        quality_report = evaluate_synthetic_data(cleaned_data, synthetic_data, metadata, target_column, dataset_name)
        quality_reports[synth_name] = quality_report  # Store results

    print("\nSynthetic Data Evaluation Completed.")
    if logger:
        logger.info(" [SYNTHETIC PIPELINE]  Synthetic Data Evaluation Completed.")

    # Save synthetic data report with quality metrics
    success = save_synthetic_data_report(output_dir, synthetic_datasets, quality_reports)
    if success:
        print("\nSynthetic Data Report Generated Successfully.")
        if logger:
            logger.info(" [SYNTHETIC PIPELINE] Synthetic Data Report Generated Successfully.")

    # Compare data distributions
    # compare_data_distributions(output_dir, cleaned_data, synthetic_datasets, target_column)
    try:
        compare_data_distributions(output_dir, cleaned_data, synthetic_datasets, target_column)
    except Exception as e:
        if logger:
            logger.error(f"[SYNTHETIC PIPELINE] Failed to compare distributions: {e}")
        else:
            print(f"[SYNTHETIC PIPELINE] Failed to compare distributions: {e}")

    return synthetic_datasets

if __name__ == "__main__":
    print("This script is not meant to be run directly. It should be called from run_benchmarks.py.")
