dataset: "C:/Users/isabe/Documents/KUL24_25/MASTER_THESIS/first_sem/datasets/crimeLAPD/Crime_Data_from_2020_to_Present.csv"
anonymized_output: "C:/Users/isabe/Documents/KUL24_25/MASTER_THESIS/first_sem/datasets/crimeLAPD/Crime_Data_anonymized.csv"

suppression_limit: 0.05

attributes:
  quasi_identifiers:
    - "Victim_age"
    - "Victim_sex"
    - "Victim_descent"
    - "LAT"
    - "LON"

  sensitive_attributes:
    - "Crime_Code"
  insensitive_attributes:
    - "DR_NO"
    - "Time_occured"
    - "Premis"
    - "Weapon"
    - "Status"


hierarchies:
  "Victim_age": "src/hierarchies/hierarchy_age_4.csv"
  "Victim_sex": "src/hierarchies/hierarchy_sex.csv"
  "Victim_descent": "src/hierarchies/hierarchy_descent.csv"

hierarchy_config:
  LAT: 10
  LON: 10

# anonym. models
models:
  k_anonymity: 3
  l_diversity:
    attribute: "Crime_Code"
    value: 2
