dataset: "C:\\Users\\isabe\\Documents\\KUL24_25\\MASTER_THESIS\\sec_sem\\datasets\\original\\bankMarketing.csv"
anonymized_output: "C:\\Users\\isabe\\Documents\\KUL24_25\\MASTER_THESIS\\sec_sem\\datasets\\original\\anonymBankMarketing.csv"

suppression_limit: 0.1

attributes:
  quasi_identifiers:
    - "age"
    - "marital"
    - "education"

  sensitive_attributes:
    - "balance"

  insensitive_attributes:
    - "contact"
    - "pdays"
    - "previous"


hierarchies:
  "age": "src/hierarchies_bankMarketing/age.csv"
  "marital": "src/hierarchies_bankMarketing/marital.csv"
  "education": "src/hierarchies_bankMarketing/education.csv"

hierarchy_config:
  {}

# anonym. models
models:
  k_anonymity: 3
  l_diversity:
    attribute: "balance"
    value: 2
